# not turing complete (yet!)
START = block END

block = (call SEP). call
call  = call expr
      | expr

expr  = '{' + block + '}'
      | '(' + call  + ')'
      | op
      | literal

op = assignment

assignment = SYMBOL '=' call
           | lambda

lambda = SYMBOL '->' call

literal = SYMBOL
        | number
        | STRING
        | BOOLEAN

number = REAL
#      | INT
