# not turing complete (yet!)
START = block END

block = (expr SEP). expr
expr  = '{' + block + '}'
      | op
      | literal

op = SYMBOL ASSIGN expr

literal = SYMBOL
        | number
        | BOOLEAN

number = REAL
